name: json_parsing_demo
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  http: ^0.12.1
  after_layout: ^1.0.7+2
  device_preview: ^0.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
